### ISSUE TITLE
Get an error when creating a page file with vite dev server

### ISSUE THREAD

**Issue by suzukey** [hannoeru/vite-plugin-pages#139]
## Overview

An error is displayed when creating a page file.

```
(node:20) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'dir')
    at PageContext.addPage (/home/projects/vitejs-vite-ooufuv/node_modules/vite-plugin-pages/dist/index.js:557:78)
    at FSWatcher.eval (/home/projects/vitejs-vite-ooufuv/node_modules/vite-plugin-pages/dist/index.js:542:18)
    at FSWatcher.EventEmitter.emit (https://vitejs-vite-ooufuv.w.staticblitz.com/blitz.bc2b78560fa0e6097e7f69d4e820659cab64d2c5.js:6:126742)
    at FSWatcher.emitWithAll (/home/projects/vitejs-vite-ooufuv/node_modules/vite/dist/node/chunks/dep-fcec4469.js:49098:8)
    at FSWatcher._emit (/home/projects/vitejs-vite-ooufuv/node_modules/vite/dist/node/chunks/dep-fcec4469.js:49190:8)
    at NodeFsHandler$1._handleFile (/home/projects/vitejs-vite-ooufuv/node_modules/vite/dist/node/chunks/dep-fcec4469.js:47788:14)
    at NodeFsHandler$1._addToNodeFs (/home/projects/vitejs-vite-ooufuv/node_modules/vite/dist/node/chunks/dep-fcec4469.js:48017:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### StackBlitz

https://stackblitz.com/edit/vitejs-vite-ooufuv

## Suggest

This error seems to occur in `watcher.on('add')`.  
When I output the log, the following conditions occurred.

```js
{
  'options.dirs': [ { dir: 'src/pages', baseRoute: '' } ]
  'path': '/home/projects/vitejs-vite-ooufuv/src/pages/test.vue',
  'page': undefined
}
```

Since the relative path and the absolute path are compared by startsWith, they do not match and are undifined.

```ts
const page = this.options.dirs.find((i) => path.startsWith(`/${i.dir}`))!
```

What do you think of this change?

```ts
const page = this.options.dirs.find((i) => path.startsWith(slash(resolve(i.dir))))!
```

Please let me know as I will send you a PR if you like.

**Comment by hannoeru** [comment]
PR welcome 👍
