### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Handpear** [hannoeru/vite-plugin-pages#143]
[vite] Internal server error: The "path" argument must be of type string. Received undefined
      at validateString (internal/validators.js:124:11)
      at parse (path.js:904:5)
      at E:\www\everqin-admin\node_modules\vite-plugin-pages\dist\index.js:355:51
      at Array.find (<anonymous>)
      at resolveReactRoutes (E:\www\everqin-admin\node_modules\vite-plugin-pages\dist\index.js:354:32)
      at PageContext.resolveRoutes (E:\www\everqin-admin\node_modules\vite-plugin-pages\dist\index.js:606:20)
      at Context.load (E:\www\everqin-admin\node_modules\vite-plugin-pages\dist\index.js:654:18)
      at Object.load (E:\www\everqin-admin\node_modules\vite\dist\node\chunks\dep-7817f5b4.js:42806:50)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async doTransform (E:\www\everqin-admin\node_modules\vite\dist\node\chunks\dep-7817f5b4.js:57515:24)
_______________________________________________________________________________________________________________________________
0.18.2 ✅
0.19.7 ❌

node v14.17.6

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by hannoeru** [comment]
What node version are you using? try v16 or above

**Comment by Handpear** [comment]
I found that the error was caused by API change
pagesDir -> dirs
I have solved the problem. Thank you

**Comment by jakeeind** [comment]
Still have the same issue
https://github.com/jakeeind/react-vite-pages-route

node v16.13.1
