### ISSUE TITLE
Don't kill dev server on "Invalid format in <route> block"

### ISSUE THREAD

**Issue by LukasKnuth** [hannoeru/vite-plugin-pages#174]
Using any supported, non JSON5 format in the `<route>` custom block of an SFC and not specifying the `lang` attribute correctly results in an error which kills `vite`:

```
Error: Invalid JSON5 format of <route> content in /mypc/src/pages/blog/an_example_post.md
JSON5: invalid character 'm' at 2:1
    at parseCustomBlock (/mypc/node_modules/vite-plugin-pages/dist/index.js:538:13)
    at getRouteBlock (/mypc/node_modules/vite-plugin-pages/dist/index.js:563:18)
    at async PageContext.checkCustomBlockChange (/mypc/node_modules/vite-plugin-pages/dist/index.js:632:25)

Node.js v17.4.0
```

(Note: I shortened the full-path from the stack-trace to only `mypc`)

**Proposal:** Don't throw this error but print it to the console. This way, the dev server doesn't die immediately.

**Comment by LukasKnuth** [comment]
This seems to originate from https://github.com/hannoeru/vite-plugin-pages/blob/main/src/customBlock.ts#L22
