### ISSUE TITLE
When deleting a file, an error will be reported

### ISSUE THREAD

**Issue by morelearn1990** [hannoeru/vite-plugin-pages#45]
```
[vite] Internal server error: /src/pages/admin/index.vue has no corresponding SFC entry in the cache. This is a @vitejs/plugin-vue internal error, please open an issue.
      at getDescriptor (/Users/morelearn/project/vite/vite-vue3/node_modules/@vitejs/plugin-vue/dist/index.js:4068:11)
      at Context.load (/Users/morelearn/project/vite/vite-vue3/node_modules/@vitejs/plugin-vue/dist/index.js:4639:28)
      at Object.load (/Users/morelearn/project/vite/vite-vue3/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:43728:50)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async transformRequest (/Users/morelearn/project/vite/vite-vue3/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:59344:24)
      at async /Users/morelearn/project/vite/vite-vue3/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:59538:32

```

Only after the `vite.config.ts` is resaved can it be reloaded normally

**Comment by hannoeru** [comment]
Can you try v0.10.0?

**Comment by morelearn1990** [comment]
The error is still there

![image](https://user-images.githubusercontent.com/18624210/116522661-072aa580-a908-11eb-9efa-3792394b304c.png)

**Comment by hannoeru** [comment]
Because you delete file that is using by your browser, vite is serving file through middleware, so it's using that file, not like webpack is serving bundled files.

As this is not related to this repo, I will close this now. You can open issue in vite's repo.
