### ISSUE TITLE
Fails when `"type": "module"` is set in `package.json`

### ISSUE THREAD

**Issue by junaga** [hannoeru/vite-plugin-pages#80]
## My setup

This is my complete setup:

```js
// vite.config.js
import { defineConfig } from "vite"
import vue from "@vitejs/plugin-vue"
import Pages from "vite-plugin-pages"

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), Pages({ pagesDir: "pages" })]
})
```

```json5
// package.json
{
  "name": "vite-project",
  "version": "0.0.0",
  "type": "module",
  "dependencies": {
    "vue": "^3.0.5",
    "vue-router": "^4.0.10"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.3.0",
    "@vue/compiler-sfc": "^3.0.5",
    "vite": "^2.4.4",
    "vite-plugin-pages": "^0.17.0"
  }
}
```

## What happens

running `npx vite ./` results in:

```sh
failed to load config from /home/junaga/gmbh/testing/vite.config.js
error when starting dev server:
TypeError: Pages is not a function
    at file:///home/junaga/gmbh/testing/vite.config.js?t=1628454664937:7:20
    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async loadConfigFromFile (/home/junaga/gmbh/testing/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:75473:31)
    at async resolveConfig (/home/junaga/gmbh/testing/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:75096:28)
    at async createServer (/home/junaga/gmbh/testing/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73625:20)
    at async CAC.<anonymous> (/home/junaga/gmbh/testing/node_modules/vite/dist/node/cli.js:13963:24)
error Command failed with exit code 1.
```

## What I expected

That vite starts the dev server, with the working plugin.

**Comment by junaga** [comment]
you rock!

**Comment by junaga** [comment]
Am I dumb? I still get the same error:

```sh
failed to load config from /home/junaga/gmbh/website/vite.config.js
error when starting dev server:
TypeError: pagesPlugin is not a function
    at file:///home/junaga/gmbh/website/vite.config.js?t=1628518181963:8:5
    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async loadConfigFromFile (/home/junaga/gmbh/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:75473:31)
    at async resolveConfig (/home/junaga/gmbh/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:75096:28)
    at async createServer (/home/junaga/gmbh/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73625:20)
    at async CAC.<anonymous> (/home/junaga/gmbh/node_modules/vite/dist/node/cli.js:13963:24)
```

**Comment by junaga** [comment]
@hannoeru Hi

I created [an repo](https://github.com/junaga/vite-plugin-pages-bug/commits/master) showing the error, from your `examples/vue/`. If you run `npm run dev` in it, it shows the exact same error `TypeError: Pages is not a function` and generates a new file `vite.config.ts.js`.

I hope this helps,
thank you and have a nice day!

**Comment by hannoeru** [comment]
Add `.default()`
```js
// vite.config.js
import { defineConfig } from "vite"
import vue from "@vitejs/plugin-vue"
import Pages from "vite-plugin-pages"

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), Pages.default({ pagesDir: "pages" })]
})
```
