### ISSUE TITLE
dynamic import async component  gets error when build

### ISSUE THREAD

**Issue by daolanfler** [hannoeru/vite-plugin-pages#97]
I'm building a blog also using vite-ssg. I have a page whose dir is like './src/pages/post/[name].vue', here I'm using the name param to dynamic import the .md component: 
```  ts 
const props = defineProps<{ name: string }>();

const { name } = toRefs(props);

const modules = import.meta.glob("../../mds/blog/*.md");

const markdown = defineAsyncComponent(
  () => import(`../../mds/blog/${name.value}.md`)
 //  modules[`../../mds/blog/${name.value}.md`]
);
``` 
it's ok to run dev, but when I run build, I've got this error: 
```
✓ 30 modules transformed.
.vite-ssg-temp/main.js                     143.25 KiB
.vite-ssg-temp/assets/style.b0296a56.css   23.43 KiB

[vite-ssg] Rendering Pages... (4)
[Vue warn]: Unhandled error during execution of async component loader 
  at <AsyncComponentWrapper ref=fn<ref> >
[Vue warn]: Unhandled error during execution of setup function 
  at <AsyncComponentWrapper ref=fn<ref> >
Error: Unknown variable dynamic import: ../../mds/blog/:name.md
    at /home/qi/documents/vite-blog/.vite-ssg-temp/main.js:446:96
    at new Promise (<anonymous>)
    at __variableDynamicImportRuntime0__ (/home/qi/documents/vite-blog/.vite-ssg-temp/main.js:445:14)
    at /home/qi/documents/vite-blog/.vite-ssg-temp/main.js:458:57
    at load (/home/qi/documents/vite-blog/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1512:17)
    at setup (/home/qi/documents/vite-blog/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1565:24)
    at callWithErrorHandling (/home/qi/documents/vite-blog/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6582:22)
    at setupStatefulComponent (/home/qi/documents/vite-blog/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6208:29)
    at setupComponent (/home/qi/documents/vite-blog/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6164:11)
    at renderComponentVNode (/home/qi/documents/vite-blog/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 
I think it's might be that the param `name` is not available in build ?  Or maybe I'm writing the wrong way, is there any workaround?

**Comment by daolanfler** [comment]
@hannoeru  [checkout this branch](https://github.com/daolanfler/vite-blog/tree/ssr_reproduce) then yarn install && yarn build shall reproduce

**Comment by hannoeru** [comment]
Because you are setting `includeAllRoutes` to `true` in `vite-ssg` options, that will include all routes including dynamic routes name. which is `:name` in here, the default option is excludes any dynamic routes.

You can check this repo https://github.com/antfu/antfu.me to see how to use markdown with SSG in Vite.

As this is not related to this plugin so I will close it.

**Comment by daolanfler** [comment]
I was understanding it wrong 😂，thanks for you suggestion!
